export enum EventTopicEnum {
  resetStore = 'resetStore',
  componentDomInit = 'componentDomInit',
  componentDomDestroy = 'componentDomDestroy',
  componentStartDragging = 'componentStartDragging',
  componentEndDragging = 'componentEndDragging',
  componentHovering = 'componentHovering',
  componentUnHovering = 'componentUnHovering',
  componentActiving = 'componentActiving',
  pluginPanelActiving = 'pluginPanelActiving',
  toolbarIntersectingChange = 'toolbarIntersectingChange',
  componentContainerScrollStart = 'componentContainerScrollStart',
  componentContainerScrollEnd = 'componentContainerScrollEnd',
  importSchema = 'importSchema',
}