export enum ComponentTypes {
  listPage = 'list-page',
  detailPage = 'detail-page',
  button = 'button',
  buttonGroup = 'button-group',
  text = 'text',
  block = 'block',
  tabs = 'tabs',
  tab = 'tab',
  table = 'table',
  tableSerialNumberColumn = 'table-serial-number-column',
  tableSelectionColumn = 'table-selection-column',
  tableOperatorColumn = 'table-operator-column',
  pagination = 'pagination',
  number = 'number',
}